// AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT. Run `pnpm tokens`.
export type Mode = "light" | "dark";

export interface Palette {
  /** Chart/page surfaces the marks sit on. */
  surface: { canvas: string; panel: string; surface: string; tile: string };
  /** Text/ink ramp — labels, values, axis text. Never a series color. */
  text: { ink: string; soft: string; mute: string; faint: string; dim: string };
  /** Fixed 8-slot categorical order, assigned by entity identity, never cycled. */
  categorical: readonly string[];
  /** One-hue light→dark ramp for magnitude (heatmaps, single-variable intensity). */
  sequential: readonly string[];
  /** Two poles + neutral gray midpoint for polarity (Δ-to-baseline). */
  diverging: { from: string; mid: string; to: string };
  /** Reserved state colors — never a series color; always paired with icon + label. */
  status: { good: string; warn: string; serious: string; critical: string };
}

export const PALETTE: Record<Mode, Palette> = {
  light: {
    surface: { canvas: "#f6f6f4", panel: "#fbfbf9", surface: "#ffffff", tile: "#ffffff" },
    text: { ink: "#14171c", soft: "#3d434e", mute: "#5b616c", faint: "#8b909b", dim: "#b0b5be" },
    categorical: ["#2a78d6", "#1baf7a", "#eda100", "#008300", "#4a3aa7", "#e34948", "#e87ba4", "#eb6834"],
    sequential: ["#5cbfa4", "#3ba888", "#288f72", "#1c745b", "#125844", "#0a3d30"],
    diverging: { from: "#2a78d6", mid: "#e9e7e2", to: "#eb6834" },
    status: { good: "#0ca30c", warn: "#d68a00", serious: "#e2632f", critical: "#d03b3b" },
  },
  dark: {
    surface: { canvas: "#06070a", panel: "#0c0e13", surface: "#0e1116", tile: "#111419" },
    text: { ink: "#eef0f3", soft: "#cfd4dd", mute: "#9aa0ab", faint: "#6a7180", dim: "#565d69" },
    categorical: ["#3987e5", "#199e70", "#c98500", "#008300", "#9085e9", "#e66767", "#d55181", "#d95926"],
    sequential: ["#bfeee1", "#8fddc9", "#5fc9ad", "#33ac8f", "#1f8a71", "#136350"],
    diverging: { from: "#3987e5", mid: "#383835", to: "#d95926" },
    status: { good: "#5fd08a", warn: "#f5c451", serious: "#ff8a5c", critical: "#ef5350" },
  },
} as const;

/**
 * Legacy brand palette — the exact pre-viz values. Kept verbatim so the
 * `COLORS` re-export in src/perflab/sim.ts stays pixel-identical until each
 * screen is migrated onto the viz layer. Prefer PALETTE[mode] in new code.
 */
export const COLORS = { lime: "#c6f135", teal: "#7bd6c0", mint: "#45d6c4", info: "#86b8ff", good: "#5fd08a", warn: "#f5c451", hot: "#ff8a5c", ink: "#eef0f3", soft: "#cfd4dd", mute: "#9aa0ab", faint: "#646b78", dim: "#565d69" } as const;
