// -----------------------------------------------------------------------------
// Token generator — the ONE step that keeps the palette from living in two places.
//
// Reads scripts/palette.data.mjs (the authored source of truth) and emits:
//   1. src/perflab/viz/tokens.ts       — PALETTE (per-mode) + legacy COLORS shim
//   2. src/viz-tokens.generated.css    — Tailwind v4 @theme tokens (dark defaults)
//
//   pnpm tokens         → write both files
//   pnpm tokens --check → regenerate in memory and diff against disk; exit 1 on
//                         drift (used by CI so the generated files can't rot).
// -----------------------------------------------------------------------------
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { paletteFor, BRAND } from "./palette.data.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const TS_PATH = resolve(ROOT, "src/perflab/viz/tokens.ts");
const CSS_PATH = resolve(ROOT, "src/viz-tokens.generated.css");

const BANNER = "AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT. Run `pnpm tokens`.";

const light = paletteFor("light");
const dark = paletteFor("dark");

// ── tokens.ts ────────────────────────────────────────────────────────────────
const arr = (a) => "[" + a.map((h) => `"${h}"`).join(", ") + "]";
const obj = (o) => "{ " + Object.entries(o).map(([k, v]) => `${k}: "${v}"`).join(", ") + " }";

function paletteLiteral(p) {
  return `{
    surface: ${obj(p.surface)},
    text: ${obj(p.text)},
    categorical: ${arr(p.categorical)},
    sequential: ${arr(p.sequential)},
    diverging: ${obj(p.diverging)},
    status: ${obj(p.status)},
  }`;
}

const ts = `// ${BANNER}
export type Mode = "light" | "dark";

export interface Palette {
  /** Chart/page surfaces the marks sit on. */
  surface: { canvas: string; panel: string; surface: string; tile: string };
  /** Text/ink ramp — labels, values, axis text. Never a series color. */
  text: { ink: string; soft: string; mute: string; faint: string; dim: string };
  /** Fixed 8-slot categorical order, assigned by entity identity, never cycled. */
  categorical: readonly string[];
  /** One-hue light→dark ramp for magnitude (heatmaps, single-variable intensity). */
  sequential: readonly string[];
  /** Two poles + neutral gray midpoint for polarity (Δ-to-baseline). */
  diverging: { from: string; mid: string; to: string };
  /** Reserved state colors — never a series color; always paired with icon + label. */
  status: { good: string; warn: string; serious: string; critical: string };
}

export const PALETTE: Record<Mode, Palette> = {
  light: ${paletteLiteral(light)},
  dark: ${paletteLiteral(dark)},
} as const;

/**
 * Legacy brand palette — the exact pre-viz values. Kept verbatim so the
 * \`COLORS\` re-export in src/perflab/sim.ts stays pixel-identical until each
 * screen is migrated onto the viz layer. Prefer PALETTE[mode] in new code.
 */
export const COLORS = ${obj(BRAND)} as const;
`;

// ── viz-tokens.generated.css ─────────────────────────────────────────────────
// Dark values are emitted as the @theme defaults (the app is dark-first today).
// Light-mode :root/.dark overrides are wired in the light-mode phase; the light
// hexes already live in tokens.ts PALETTE.light for the SVG layer to consume.
const cssLines = [];
dark.categorical.forEach((h, i) => cssLines.push(`  --color-cat-${i + 1}: ${h};`));
dark.sequential.forEach((h, i) => cssLines.push(`  --color-seq-${i + 1}: ${h};`));
for (const [k, v] of Object.entries(dark.status)) cssLines.push(`  --color-status-${k}: ${v};`);
for (const [k, v] of Object.entries(dark.diverging)) cssLines.push(`  --color-diverge-${k}: ${v};`);

const css = `/* ${BANNER} */
/* Data-viz palette tokens. Dark defaults; light-mode overrides land in the light phase. */
@theme {
${cssLines.join("\n")}
}
`;

// ── write or check ───────────────────────────────────────────────────────────
const check = process.argv.includes("--check");
const targets = [
  { path: TS_PATH, content: ts, name: "src/perflab/viz/tokens.ts" },
  { path: CSS_PATH, content: css, name: "src/viz-tokens.generated.css" },
];

let drift = false;
for (const t of targets) {
  if (check) {
    let current = "";
    try { current = readFileSync(t.path, "utf8"); } catch { /* missing → drift */ }
    if (current !== t.content) {
      drift = true;
      console.error(`[tokens] DRIFT: ${t.name} is stale — run \`pnpm tokens\``);
    } else {
      console.log(`[tokens] ok: ${t.name}`);
    }
  } else {
    writeFileSync(t.path, t.content);
    console.log(`[tokens] wrote ${t.name}`);
  }
}

if (check && drift) process.exit(1);
