/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create new user + empty AthleteProfile.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Metrics */
        post: operations["compute_metrics_compute_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Simple health check endpoint.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Program */
        get: operations["get_run_program_program_run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program/strength": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strength Program */
        get: operations["get_strength_program_program_strength_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benchmarks/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Benchmark Definitions */
        get: operations["get_benchmark_definitions_v1_benchmarks_definitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benchmarks/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Benchmark Observations */
        get: operations["get_benchmark_observations_v1_benchmarks_observations_get"];
        put?: never;
        /** Post Benchmark Observation */
        post: operations["post_benchmark_observation_v1_benchmarks_observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benchmarks/recompute-derived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Recompute Derived */
        post: operations["post_recompute_derived_v1_benchmarks_recompute_derived_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/domain-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Domain Summary */
        get: operations["get_domain_summary_v1_dashboard_domain_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Kpis */
        get: operations["get_dashboard_kpis_v1_dashboard_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Readiness */
        get: operations["get_readiness_v1_dashboard_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/log-workout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Workout */
        post: operations["log_workout_v1_log_workout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/next-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Next Session
         * @description DEV-friendly version that auto-initializes baseline state.
         */
        get: operations["get_next_session_v1_next_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/onboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboard Athlete */
        post: operations["onboard_athlete_v1_onboard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/planning/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blocks */
        get: operations["list_blocks_v1_planning_blocks_get"];
        put?: never;
        /** Create Block */
        post: operations["create_block_v1_planning_blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/planning/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Block */
        patch: operations["update_block_v1_planning_blocks__block_id__patch"];
        trace?: never;
    };
    "/v1/planning/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_v1_planning_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/planning/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_v1_planning_sessions__session_id__patch"];
        trace?: never;
    };
    "/v1/planning/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_v1_planning_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulate-dose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Dose */
        post: operations["simulate_dose_v1_simulate_dose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/weak-points/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Weak Points
         * @description Return all weak-point rows for the current user.
         *
         *     By default only active (unresolved) rows are returned.
         *     Pass active_only=false to include resolved rows.
         */
        get: operations["list_weak_points_v1_weak_points__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/weak-points/{weak_point_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Weak Point
         * @description Hard-delete a weak-point row owned by the current user.
         *
         *     Returns 204 No Content on success, 404 if not found or wrong user.
         */
        delete: operations["delete_weak_point_v1_weak_points__weak_point_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Weak Point
         * @description Update confidence, note, and/or resolved_at on a weak-point row.
         *
         *     Only fields explicitly present in the request body are applied.
         *     Sending resolved_at=null re-opens a resolved weak point.
         */
        patch: operations["patch_weak_point_v1_weak_points__weak_point_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdaptationContribution
         * @description Per-session adaptation signal by capacity axis.
         *
         *     Computed by the dose engine from aggregated phi_adapt vectors and session
         *     load. Consumed by state_update to drive explicit capacity gains.
         */
        AdaptationContribution: {
            /**
             * Aerobic
             * @default 0
             */
            aerobic: number;
            /**
             * Glycolytic
             * @default 0
             */
            glycolytic: number;
            /**
             * Hypertrophy
             * @default 0
             */
            hypertrophy: number;
            /**
             * Max Strength
             * @default 0
             */
            max_strength: number;
            /**
             * Mobility
             * @default 0
             */
            mobility: number;
            /**
             * Power
             * @default 0
             */
            power: number;
            /**
             * Skill
             * @default 0
             */
            skill: number;
            /**
             * Work Capacity
             * @default 0
             */
            work_capacity: number;
        };
        /** AnchorObservationOut */
        AnchorObservationOut: {
            /** Benchmark Code */
            benchmark_code: string;
            /** Domain */
            domain: string;
            /** Is Primary Anchor */
            is_primary_anchor: boolean;
            /** Metric Type */
            metric_type: string;
            /** Name */
            name: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Raw Value */
            raw_value: number;
            /** Unit */
            unit: string;
        };
        /** BenchmarkDefinitionRead */
        BenchmarkDefinitionRead: {
            /** Better Direction */
            better_direction: string;
            /** Code */
            code: string;
            /** Domain */
            domain: string;
            /** Fatigue Targets */
            fatigue_targets: string[] | null;
            /** Id */
            id: number;
            /** Is Derived Only */
            is_derived_only: boolean;
            /** Is Primary Anchor */
            is_primary_anchor: boolean;
            /** Is Validator Only */
            is_validator_only: boolean;
            /** Metric Type */
            metric_type: string;
            /** Name */
            name: string;
            /** Observation Weight */
            observation_weight: number;
            /** Protocol Summary */
            protocol_summary: string | null;
            /** State Targets */
            state_targets: string[] | null;
            /** Tissue Targets */
            tissue_targets: string[] | null;
            /** Unit */
            unit: string;
        };
        /** BenchmarkObservationCreate */
        BenchmarkObservationCreate: {
            /**
             * Benchmark Code
             * @description Stable code from benchmark_definitions
             */
            benchmark_code: string;
            /** Bodyweight Kg */
            bodyweight_kg?: number | null;
            /** Heart Rate Avg */
            heart_rate_avg?: number | null;
            /** Heart Rate Drift Pct */
            heart_rate_drift_pct?: number | null;
            /** Normalized Value */
            normalized_value?: number | null;
            /** Notes */
            notes?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Protocol Metadata */
            protocol_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Raw Value */
            raw_value: number;
            /** Rpe */
            rpe?: number | null;
            /** Secondary Value */
            secondary_value?: number | null;
            /**
             * Source
             * @default manual
             */
            source: string;
            /**
             * Validity Status
             * @default valid
             */
            validity_status: string;
        };
        /** BenchmarkObservationRead */
        BenchmarkObservationRead: {
            /** Benchmark Code */
            benchmark_code: string;
            /** Benchmark Definition Id */
            benchmark_definition_id: number;
            /** Id */
            id: number;
            /** Normalized Value */
            normalized_value: number | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Raw Value */
            raw_value: number;
            /** Secondary Value */
            secondary_value: number | null;
            /** Source */
            source: string;
            /** User Id */
            user_id: number;
            /** Validity Status */
            validity_status: string;
        };
        /** BlockCreateRequest */
        BlockCreateRequest: {
            /**
             * Benchmark Every N Weeks
             * @default 4
             */
            benchmark_every_n_weeks: number | null;
            /**
             * Deload Every N Weeks
             * @default 4
             */
            deload_every_n_weeks: number;
            /**
             * Deload Volume Factor
             * @default 0.6
             */
            deload_volume_factor: number;
            /**
             * Duration Weeks
             * @default 8
             */
            duration_weeks: number;
            goal: components["schemas"]["BlockGoal"];
            /** Modality Mix */
            modality_mix?: {
                [key: string]: number;
            };
            /** Rationale */
            rationale?: string | null;
            /**
             * Sessions Per Week
             * @default 3
             */
            sessions_per_week: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Weekly Template */
            weekly_template?: components["schemas"]["WeeklyTemplateSlot"][];
        };
        /**
         * BlockGoal
         * @enum {string}
         */
        BlockGoal: "Strength" | "Hypertrophy" | "Power" | "Hyrox" | "CrossFit" | "Running" | "Calisthenics" | "General" | "Recomp";
        /** BlockRead */
        BlockRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deload Every N Weeks */
            deload_every_n_weeks: number;
            /** Deload Volume Factor */
            deload_volume_factor: number;
            /** Duration Weeks */
            duration_weeks: number;
            /** End Date */
            end_date: string | null;
            goal: components["schemas"]["BlockGoal"];
            /** Id */
            id: number;
            /** Modality Mix */
            modality_mix: {
                [key: string]: unknown;
            };
            /** Rationale */
            rationale: string | null;
            /** Sessions Per Week */
            sessions_per_week: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            status: components["schemas"]["BlockStatus"];
            /** User Id */
            user_id: number;
            /** Weekly Template */
            weekly_template: {
                [key: string]: unknown;
            }[];
        };
        /**
         * BlockStatus
         * @enum {string}
         */
        BlockStatus: "active" | "completed" | "abandoned";
        /** BlockUpdateRequest */
        BlockUpdateRequest: {
            /** Rationale */
            rationale?: string | null;
            status?: components["schemas"]["BlockStatus"] | null;
        };
        /** Body_login_auth_token_post */
        Body_login_auth_token_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /**
         * CapacityState
         * @description X_t — capacity / adaptation ceiling components (higher = better).
         */
        CapacityState: {
            /**
             * Aerobic
             * @description Aerobic / CS–VO2 proxy
             * @default 300
             */
            aerobic: number;
            /**
             * Glycolytic
             * @description Glycolytic / W′-style reserve
             * @default 50
             */
            glycolytic: number;
            /**
             * Hypertrophy
             * @default 50
             */
            hypertrophy: number;
            /**
             * Max Strength
             * @default 100
             */
            max_strength: number;
            /**
             * Mobility
             * @default 50
             */
            mobility: number;
            /**
             * Power
             * @default 50
             */
            power: number;
            /**
             * Skill
             * @default 50
             */
            skill: number;
            /**
             * Work Capacity
             * @default 50
             */
            work_capacity: number;
        };
        /**
         * DashboardBundleOut
         * @description Latest primary-anchor observations plus derived KPI snapshots.
         */
        DashboardBundleOut: {
            /** Kpis */
            kpis: components["schemas"]["KPIValueOut"][];
            /** Primary Anchors */
            primary_anchors: components["schemas"]["AnchorObservationOut"][];
        };
        /** DomainSummaryOut */
        DomainSummaryOut: {
            /** Domain */
            domain: string;
            /** Kpis */
            kpis: components["schemas"]["KPIValueOut"][];
            /** Primary Anchors */
            primary_anchors: components["schemas"]["AnchorObservationOut"][];
        };
        /**
         * ExerciseEntry
         * @description A single exercise within a session log.
         *
         *     `phi_*` and `energy_mix` are resolved from the Exercise DB row by the
         *     service layer before the dose engine runs. They are left blank in
         *     client-submitted logs; the engine falls back to modality defaults when absent.
         */
        ExerciseEntry: {
            /** Avg Rir */
            avg_rir?: number | null;
            /** Avg Rpe */
            avg_rpe?: number | null;
            /** Distance Meters */
            distance_meters?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Energy Mix */
            energy_mix?: {
                [key: string]: unknown;
            } | null;
            /** Exercise Id */
            exercise_id?: number | null;
            /** Exercise Name */
            exercise_name?: string | null;
            /** Impact Level */
            impact_level?: number | null;
            /** Load Kg */
            load_kg?: number | null;
            /** Modality */
            modality?: string | null;
            /** Movement Pattern */
            movement_pattern?: string | null;
            /** Phi Adapt */
            phi_adapt?: {
                [key: string]: unknown;
            } | null;
            /** Phi Fatigue */
            phi_fatigue?: {
                [key: string]: unknown;
            } | null;
            /** Phi Tissue */
            phi_tissue?: {
                [key: string]: unknown;
            } | null;
            /** Recovery Cost */
            recovery_cost?: number | null;
            /** Reps */
            reps?: number | null;
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Sets */
            sets?: number | null;
            /** Skill Demand */
            skill_demand?: number | null;
            /** Sport Domains */
            sport_domains?: string[] | null;
            /** Tempo */
            tempo?: string | null;
            /** Weak Point Tags */
            weak_point_tags?: string[] | null;
        };
        /**
         * ExercisePrescription
         * @description A single prescribed exercise within a session.
         */
        ExercisePrescription: {
            /** Load Note */
            load_note?: string | null;
            /** Name */
            name: string;
            /** Reps */
            reps?: string | null;
            /** Sets */
            sets?: number | null;
            /** Weak Point Tags */
            weak_point_tags?: string[];
        };
        /**
         * FatigueState
         * @description F_t — multi-component fatigue (0–100). Higher = more fatigued.
         */
        FatigueState: {
            /**
             * Cns
             * @default 0
             */
            cns: number;
            /**
             * Grip
             * @default 0
             */
            grip: number;
            /**
             * Metabolic
             * @default 0
             */
            metabolic: number;
            /**
             * Muscular
             * @default 0
             */
            muscular: number;
            /**
             * Structural
             * @default 0
             */
            structural: number;
            /**
             * Tendon
             * @default 0
             */
            tendon: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KPIValueOut */
        KPIValueOut: {
            /** Can Affect Prescriber Rules */
            can_affect_prescriber_rules: boolean;
            /** Code */
            code: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Confidence */
            confidence: number | null;
            /** Domain */
            domain: string;
            /** Is Dashboard Kpi */
            is_dashboard_kpi: boolean;
            /** Metric Type */
            metric_type: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** MetricsRequest */
        MetricsRequest: {
            /** Age */
            age: number;
            /** Sex */
            sex: string;
            /** Time 1P5Mi */
            time_1p5mi: string;
            /** Time 300M */
            time_300m: string;
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Fatigue Percent */
            fatigue_percent: number;
            /** Fatigue Profile */
            fatigue_profile: string;
            /** Race Pace Sec Per Mile */
            race_pace_sec_per_mile: number;
            /** Result Category */
            result_category: string;
            /** Vo2 Category */
            vo2_category: string;
            /** Vo2 Max */
            vo2_max: number;
            /** Zones */
            zones: components["schemas"]["Zone"][];
        };
        /** OnboardRequest */
        OnboardRequest: {
            /**
             * Available Days Per Week
             * @default 3
             */
            available_days_per_week: number;
            /** Bench 1Rm Kg */
            bench_1rm_kg?: number | null;
            /** Bodyweight Kg */
            bodyweight_kg?: number | null;
            /** Deadlift 1Rm Kg */
            deadlift_1rm_kg?: number | null;
            /** Equipment */
            equipment?: string[];
            /**
             * Experience Level
             * @default intermediate
             */
            experience_level: string;
            /**
             * Experience Years
             * @default 0
             */
            experience_years: number;
            /**
             * Goal
             * @default Strength
             */
            goal: string;
            /** Run 5K Seconds */
            run_5k_seconds?: number | null;
            /** Self Reported Weak Points */
            self_reported_weak_points?: string[];
            /**
             * Session Duration Minutes
             * @default 60
             */
            session_duration_minutes: number;
            /** Squat 1Rm Kg */
            squat_1rm_kg?: number | null;
        };
        /** OnboardResponse */
        OnboardResponse: {
            /** Message */
            message: string;
            /**
             * Next Step
             * @default Call GET /v1/next-session?goal=Strength to get first prescription
             */
            next_step: string;
            /** Profile Id */
            profile_id: number;
            /** User Id */
            user_id: number;
        };
        /** PlannedSessionRead */
        PlannedSessionRead: {
            /** Benchmark Key */
            benchmark_key?: string | null;
            /** Block Id */
            block_id: number;
            /** Category */
            category: string;
            /** Completed At */
            completed_at?: string | null;
            /** Day Of Week */
            day_of_week: number;
            /** Id */
            id: number;
            /** Is Benchmark */
            is_benchmark: boolean;
            /** Is Deload */
            is_deload: boolean;
            /** Modality */
            modality: string;
            /** Prescribed Content */
            prescribed_content?: {
                [key: string]: unknown;
            } | null;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            status: components["schemas"]["SessionStatus"];
            /** User Id */
            user_id: number;
            /** Week Number */
            week_number: number;
            /** Workout Log Id */
            workout_log_id?: number | null;
        };
        /** PlannedSessionUpdateRequest */
        PlannedSessionUpdateRequest: {
            /** Scheduled Date */
            scheduled_date?: string | null;
            status?: components["schemas"]["SessionStatus"] | null;
        };
        /**
         * PrescriptionExplanation
         * @description Why this session — state drivers, constraints, sources.
         */
        PrescriptionExplanation: {
            /** Constraints Applied */
            constraints_applied?: string[];
            /**
             * Goal Alignment
             * @default
             */
            goal_alignment: string;
            /**
             * Prescription Branch
             * @description Internal prescriber branch id (safety, readiness, goal path)
             */
            prescription_branch?: string | null;
            /**
             * Score
             * @description Template-aligned fit score vs twin state (0–1)
             */
            score?: number | null;
            /**
             * Source Alignment
             * @description Human-readable: templates + primitives + models
             */
            source_alignment?: string[];
            /** State Drivers */
            state_drivers?: string[];
            /**
             * Structured Template Name
             * @description Display name for structured coaching template (v2)
             */
            structured_template_name?: string | null;
            /** Template Id */
            template_id?: string | null;
            validation?: components["schemas"]["ValidationSummary"] | null;
            /**
             * Warnings
             * @description Soft constraint / template warnings (non-blocking)
             */
            warnings?: string[];
        };
        /** ReadinessOut */
        ReadinessOut: {
            /**
             * Kpi Flags
             * @description Soft signals from KPIs (e.g. elevated run fatigue factor)
             */
            kpi_flags?: {
                [key: string]: unknown;
            };
            state: components["schemas"]["UnifiedStateVector"] | null;
        };
        /** RecomputeDerivedResponse */
        RecomputeDerivedResponse: {
            /** Codes Computed */
            codes_computed: string[];
            /** Snapshots Written */
            snapshots_written: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RunSession */
        RunSession: {
            /** Day */
            day: string;
            /** Focus */
            focus: string;
            /** Name */
            name: string;
            /** Rpe */
            rpe: string;
            /** Session */
            session: number;
            /** Week */
            week: number;
            /** Zone */
            zone: string;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "pending" | "completed" | "skipped" | "rescheduled";
        /** StrengthSession */
        StrengthSession: {
            /** Accessory */
            accessory: string;
            /** Day */
            day: string;
            /** Main Lifts */
            main_lifts: string;
            /** Notes */
            notes: string;
            /** Phase */
            phase: string;
            /** Week */
            week: number;
        };
        /**
         * StressDose
         * @description Stress dose: six-dimensional engine vector plus legacy scalars for clients.
         *
         *     `adaptation_contribution` is the session's positive adaptation signal per
         *     capacity axis. Used by state_update for explicit capacity gains.
         */
        StressDose: {
            adaptation_contribution?: components["schemas"]["AdaptationContribution"];
            /**
             * D Met Systemic
             * @default 0
             */
            d_met_systemic: number;
            /**
             * D Nm Central
             * @default 0
             */
            d_nm_central: number;
            /**
             * D Nm Peripheral
             * @default 0
             */
            d_nm_peripheral: number;
            /**
             * D Struct Damage
             * @default 0
             */
            d_struct_damage: number;
            /**
             * D Struct Signal
             * @default 0
             */
            d_struct_signal: number;
            dose_six?: components["schemas"]["StressDoseSix"];
        };
        /**
         * StressDoseSix
         * @description D_t — session stress dose in six dimensions (non-negative).
         */
        StressDoseSix: {
            /**
             * Density
             * @default 0
             */
            density: number;
            /**
             * Impact
             * @default 0
             */
            impact: number;
            /**
             * Intensity
             * @default 0
             */
            intensity: number;
            /**
             * Metabolic
             * @default 0
             */
            metabolic: number;
            /**
             * Skill
             * @default 0
             */
            skill: number;
            /**
             * Volume
             * @default 0
             */
            volume: number;
        };
        /**
         * TissueState
         * @description T_t — accumulated tissue / structural stress (0–100).
         */
        TissueState: {
            /**
             * Ankle
             * @default 0
             */
            ankle: number;
            /**
             * Elbow
             * @default 0
             */
            elbow: number;
            /**
             * Finger
             * @default 0
             */
            finger: number;
            /**
             * Hip
             * @default 0
             */
            hip: number;
            /**
             * Knee
             * @default 0
             */
            knee: number;
            /**
             * Lumbar
             * @default 0
             */
            lumbar: number;
            /**
             * Shoulder
             * @default 0
             */
            shoulder: number;
            /**
             * Wrist
             * @default 0
             */
            wrist: number;
        };
        /** TodaySessionResponse */
        TodaySessionResponse: {
            /** Prescription */
            prescription?: {
                [key: string]: unknown;
            } | null;
            session: components["schemas"]["PlannedSessionRead"] | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UnifiedStateVector
         * @description Digital twin snapshot S(t): legacy scalars + decomposed engine vectors.
         *
         *     Legacy fields remain for backward-compatible API clients; they are derived
         *     from (capacity_x, fatigue_f, tissue_t) on each update.
         */
        UnifiedStateVector: {
            /**
             * B Met Anaerobic
             * @description Anaerobic work capacity (W'/D')
             */
            b_met_anaerobic: number;
            /**
             * C Met Aerobic
             * @description Aerobic capacity (e.g. CS / VO2 proxy)
             */
            c_met_aerobic: number;
            /**
             * C Nm Force
             * @description Maximal strength / force capacity
             */
            c_nm_force: number;
            /**
             * C Struct
             * @description Structural capacity / CSA proxy
             */
            c_struct: number;
            capacity_x?: components["schemas"]["CapacityState"];
            /**
             * F Met Systemic
             * @default 0
             */
            f_met_systemic: number;
            /**
             * F Nm Central
             * @default 0
             */
            f_nm_central: number;
            /**
             * F Nm Peripheral
             * @default 0
             */
            f_nm_peripheral: number;
            /**
             * F Struct Damage
             * @default 0
             */
            f_struct_damage: number;
            fatigue_f?: components["schemas"]["FatigueState"];
            /**
             * Habit Strength
             * @default 0
             */
            habit_strength: number;
            /**
             * Model Version
             * @description State engine version
             * @default v0.3
             */
            model_version: string;
            /**
             * S Struct Signal
             * @default 0
             */
            s_struct_signal: number;
            /** Skill State */
            skill_state?: {
                [key: string]: number;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            tissue_t?: components["schemas"]["TissueState"];
        };
        /** UserResponse */
        UserResponse: {
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationSummary
         * @description Result of validate_session checks.
         */
        ValidationSummary: {
            /** Failed Checks */
            failed_checks?: string[];
            /** Hard Violations */
            hard_violations?: string[];
            /** Passed */
            passed: boolean;
        };
        /** WeakPointOut */
        WeakPointOut: {
            /** Confidence */
            confidence: number;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Note */
            note: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Source */
            source: string;
            /** Tag */
            tag: string;
        };
        /** WeakPointPatch */
        WeakPointPatch: {
            /** Confidence */
            confidence?: number | null;
            /** Note */
            note?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** WeeklyTemplateSlot */
        WeeklyTemplateSlot: {
            /** Category */
            category: string;
            /** Day Of Week */
            day_of_week: number;
            /** Modality */
            modality: string;
        };
        /**
         * WorkoutLog
         * @description Raw input log (Sensor Data).
         */
        WorkoutLog: {
            /** Avg Rir */
            avg_rir?: number | null;
            /**
             * Benchmark Results
             * @description Optional benchmark key/value payload for benchmark sessions.
             */
            benchmark_results?: {
                [key: string]: unknown;
            } | null;
            /**
             * Distance Meters
             * @default 0
             */
            distance_meters: number | null;
            /**
             * Dominant Movement Pattern
             * @description e.g. squat | hinge | run — defaults inferred from modality
             */
            dominant_movement_pattern?: string | null;
            /** Duration Minutes */
            duration_minutes: number;
            /**
             * Estimated Sets
             * @description If set, refines volume term in dose law
             */
            estimated_sets?: number | null;
            /**
             * Exercises
             * @description Per-exercise breakdown. When present, dose reflects actual exercise phi vectors.
             */
            exercises?: components["schemas"]["ExerciseEntry"][];
            /**
             * Is Benchmark
             * @default false
             */
            is_benchmark: boolean;
            /**
             * Life Stress Inverse
             * @description 1 = Very high life stress, 10 = No life stress
             * @default 5
             */
            life_stress_inverse: number;
            /**
             * Modality
             * @enum {string}
             */
            modality: "Running" | "Strength" | "Hypertrophy" | "Power" | "Mixed";
            /**
             * Novelty
             * @description >1 = novel / high coordination demand for this athlete
             * @default 1
             */
            novelty: number;
            /**
             * Planned Session Id
             * @description If provided, marks this log as fulfillment of the planned session.
             */
            planned_session_id?: number | null;
            /** Session Rpe */
            session_rpe: number;
            /**
             * Sleep Quality
             * @default 5
             */
            sleep_quality: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Total Volume Load
             * @default 0
             */
            total_volume_load: number | null;
        };
        /**
         * WorkoutPrescription
         * @description Next-session recommendation. Legacy fields required; `why` optional for old clients.
         */
        WorkoutPrescription: {
            /** Duration Min */
            duration_min: number;
            /** Exercises */
            exercises?: components["schemas"]["ExercisePrescription"][];
            /** Focus */
            focus: string;
            /**
             * Model Version
             * @description Prescription engine version
             * @default v0.3
             */
            model_version: string;
            /** Rationale */
            rationale: string;
            /** Type */
            type: string;
            why?: components["schemas"]["PrescriptionExplanation"] | null;
        };
        /** Zone */
        Zone: {
            /** Fast Offset Sec */
            fast_offset_sec: number;
            /** Fast Pace Sec */
            fast_pace_sec: number;
            /** Name */
            name: string;
            /** Notes */
            notes: string;
            /** Slow Offset Sec */
            slow_offset_sec: number;
            /** Slow Pace Sec */
            slow_pace_sec: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_metrics_compute_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_run_program_program_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSession"][];
                };
            };
        };
    };
    get_strength_program_program_strength_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrengthSession"][];
                };
            };
        };
    };
    get_benchmark_definitions_v1_benchmarks_definitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkDefinitionRead"][];
                };
            };
        };
    };
    get_benchmark_observations_v1_benchmarks_observations_get: {
        parameters: {
            query?: {
                benchmark_code?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkObservationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_benchmark_observation_v1_benchmarks_observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkObservationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkObservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_recompute_derived_v1_benchmarks_recompute_derived_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeDerivedResponse"];
                };
            };
        };
    };
    get_domain_summary_v1_dashboard_domain_summary_get: {
        parameters: {
            query: {
                domain: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_kpis_v1_dashboard_kpis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardBundleOut"];
                };
            };
        };
    };
    get_readiness_v1_dashboard_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"];
                };
            };
        };
    };
    log_workout_v1_log_workout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutLog"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedStateVector"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_session_v1_next_session_get: {
        parameters: {
            query?: {
                /** @description Training goal to prescribe for; defaults to the athlete's primary goal. */
                goal?: "Strength" | "Hypertrophy" | "Power" | "General" | "OlympicLifts" | "Powerlifting" | "MetCon" | "Calisthenics" | "Gymnastics" | "Grip" | "Running" | "Sprinting" | "HalfMarathon" | "FullMarathon";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPrescription"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboard_athlete_v1_onboard_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blocks_v1_planning_blocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockRead"][];
                };
            };
        };
    };
    create_block_v1_planning_blocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_block_v1_planning_blocks__block_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_planning_sessions_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedSessionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_v1_planning_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedSessionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_v1_planning_today_get: {
        parameters: {
            query?: {
                goal?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodaySessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_dose_v1_simulate_dose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutLog"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StressDose"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_weak_points_v1_weak_points__get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeakPointOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_weak_point_v1_weak_points__weak_point_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weak_point_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_weak_point_v1_weak_points__weak_point_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weak_point_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeakPointPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeakPointOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
