"""v1 vs v0 dose comparison matrix — the evidence the phase-8 re-fit needs.

Answers one question: **is v1 merely scaled differently, or does it change rank order?**

A scale difference is calibratable — fit a coefficient and the model agrees again. A rank
inversion is not: if two sessions formerly ranked A > B come out B > A, no coefficient
restores the old ordering, because the predictor is saying something different about the
athlete. So this script reports both, and rank inversions are the headline.

The grid is synthetic and deterministic. That is a deliberate limit: it shows where the two
models diverge across the input space, NOT how either maps to real adaptation. Fitting against
this output would be fitting against a placeholder — phase 8B needs logged athlete data.

Run:
    uv run python -m app.scripts.compare_dose_models
    uv run python -m app.scripts.compare_dose_models --out docs/simulations/dose-v0-v1.md
"""
from __future__ import annotations

import argparse
import itertools
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from app.logic import dose_engine_v0 as v0
from app.logic import dose_engine_v1 as v1
from app.schemas.workouts import WorkoutLog

_WHEN = datetime(2026, 1, 1, 9, 0, tzinfo=UTC)

MODALITIES = ("Strength", "Hypertrophy", "Power", "Running", "Mixed")
DURATION_BUCKETS = ((30.0, "short"), (60.0, "medium"), (95.0, "long"))
SET_BUCKETS = ((None, "unreported"), (8.0, "few"), (20.0, "typical"), (34.0, "many"))
EFFORT_BUCKETS = ((5.0, "easy"), (7.5, "medium"), (9.0, "hard"))


@dataclass(frozen=True)
class Row:
    modality: str
    duration_label: str
    sets_label: str
    effort_label: str
    v0_total: float
    v1_total: float

    @property
    def ratio(self) -> float:
        return self.v1_total / self.v0_total if self.v0_total else float("inf")


def _log(modality: str, duration: float, sets: float | None, rpe: float) -> WorkoutLog:
    return WorkoutLog(
        timestamp=_WHEN,
        modality=modality,
        duration_minutes=duration,
        session_rpe=rpe,
        estimated_sets=sets,
        total_volume_load=(sets or 0.0) * 400.0,
        sleep_quality=7.0,
        life_stress_inverse=7.0,
    )


def _total(dose) -> float:
    return sum(dose.dose_six.model_dump().values())


def build_matrix() -> list[Row]:
    rows: list[Row] = []
    for modality, (duration, d_label), (sets, s_label), (rpe, e_label) in itertools.product(
        MODALITIES, DURATION_BUCKETS, SET_BUCKETS, EFFORT_BUCKETS
    ):
        log = _log(modality, duration, sets, rpe)
        rows.append(
            Row(
                modality=modality,
                duration_label=d_label,
                sets_label=s_label,
                effort_label=e_label,
                v0_total=_total(v0.calculate_stress_dose(log)),
                v1_total=_total(v1.calculate_stress_dose(log)),
            )
        )
    return rows


def _differing_factors(left: Row, right: Row) -> list[str]:
    factors = []
    if left.modality != right.modality:
        factors.append("modality")
    if left.duration_label != right.duration_label:
        factors.append("duration")
    if left.sets_label != right.sets_label:
        factors.append("sets")
    if left.effort_label != right.effort_label:
        factors.append("effort")
    return factors


def rank_inversions(rows: list[Row]) -> list[tuple[Row, Row, str]]:
    """CONTROLLED pairs whose order differs between the models.

    Only pairs differing in exactly ONE factor are compared. Ranking a strength session
    against a run is not a claim either model makes — counting those as "inversions" produces
    a large number that means nothing. A controlled inversion is the real signal: it says the
    two models disagree about the effect of that single variable, which no coefficient fixes.
    """
    inversions: list[tuple[Row, Row, str]] = []
    for left, right in itertools.combinations(rows, 2):
        factors = _differing_factors(left, right)
        if len(factors) != 1:
            continue
        if (left.v0_total - right.v0_total) * (left.v1_total - right.v1_total) < 0:
            inversions.append((left, right, factors[0]))
    return inversions


def controlled_pairs(rows: list[Row]) -> int:
    return sum(
        1
        for left, right in itertools.combinations(rows, 2)
        if len(_differing_factors(left, right)) == 1
    )


def render(rows: list[Row]) -> str:
    inversions = rank_inversions(rows)
    ratios = sorted(r.ratio for r in rows)
    lines = [
        "# Dose model comparison — v1 (work per elapsed time) vs v0 (minutes per set)",
        "",
        "Generated by `app/scripts/compare_dose_models.py` over a synthetic grid.",
        "**Synthetic**: this shows where the models diverge, not how either maps to adaptation.",
        "",
        f"- sessions compared: **{len(rows)}**",
        f"- v1/v0 dose ratio: min **{ratios[0]:.2f}x**, median **{ratios[len(ratios)//2]:.2f}x**, "
        f"max **{ratios[-1]:.2f}x**",
        f"- controlled rank inversions: **{len(inversions)}** of {controlled_pairs(rows)} "
        "pairs differing in exactly one factor",
        "",
        "## Ratio by modality",
        "",
        "| modality | min | median | max |",
        "|---|---|---|---|",
    ]
    for modality in MODALITIES:
        subset = sorted(r.ratio for r in rows if r.modality == modality)
        lines.append(
            f"| {modality} | {subset[0]:.2f}x | {subset[len(subset)//2]:.2f}x | {subset[-1]:.2f}x |"
        )

    lines += ["", "## Ratio by set-count bucket", "", "| sets | min | median | max |", "|---|---|---|---|"]
    for _sets, label in SET_BUCKETS:
        subset = sorted(r.ratio for r in rows if r.sets_label == label)
        lines.append(
            f"| {label} | {subset[0]:.2f}x | {subset[len(subset)//2]:.2f}x | {subset[-1]:.2f}x |"
        )

    lines += ["", "## Ratio by duration bucket", "", "| duration | min | median | max |", "|---|---|---|---|"]
    for _duration, label in DURATION_BUCKETS:
        subset = sorted(r.ratio for r in rows if r.duration_label == label)
        lines.append(
            f"| {label} | {subset[0]:.2f}x | {subset[len(subset)//2]:.2f}x | {subset[-1]:.2f}x |"
        )

    lines += ["", "## Controlled rank inversions", ""]
    lines.append("Pairs differing in exactly ONE factor whose order swaps between the models.")
    lines.append("Scale differences are calibratable; these are not.")
    lines.append("")
    if not inversions:
        lines.append("None: v1 preserves v0's ordering on every controlled comparison, so the")
        lines.append("difference is one of scale — which is what calibration addresses.")
    else:
        by_factor: dict[str, int] = {}
        for _left, _right, factor in inversions:
            by_factor[factor] = by_factor.get(factor, 0) + 1
        lines.append("| factor varied | inversions |")
        lines.append("|---|---|")
        for factor, count in sorted(by_factor.items(), key=lambda kv: -kv[1]):
            lines.append(f"| {factor} | {count} |")
        lines.append("")
        lines.append("First 20:")
        lines.append("")
        lines.append("| factor | A | B | v0 | v1 |")
        lines.append("|---|---|---|---|---|")
        for left, right, factor in inversions[:20]:
            a = f"{left.modality}/{left.duration_label}/{left.sets_label}/{left.effort_label}"
            b = f"{right.modality}/{right.duration_label}/{right.sets_label}/{right.effort_label}"
            lines.append(
                f"| {factor} | {a} | {b} | {left.v0_total:.2f} vs {right.v0_total:.2f} | "
                f"{left.v1_total:.2f} vs {right.v1_total:.2f} |"
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="Compare dose engine v1 against v0.")
    ap.add_argument("--out", type=Path, default=None, help="write the report to this path")
    args = ap.parse_args()

    report = render(build_matrix())
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(report, encoding="utf-8")
        print(f"[compare_dose_models] wrote {args.out}")
    else:
        print(report)


if __name__ == "__main__":
    main()
